{
 "title": "Temperature Grafana GCP",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "History",
   "type": "graph",
   "gridPos": { "h": 16, "w": 8, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "temperature_gauge", "legendFormat": "Temperature" }
   ]
  },
  {
   "title": "Instant",
   "type": "stat",
   "gridPos": { "h": 16, "w": 6, "x": 8, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    { "expr": "temperature_gauge", "legendFormat": "Temperature" }
   ]
  },
  {
   "title": "Max Value",
   "type": "stat",
   "gridPos": { "h": 8, "w": 4, "x": 14, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "max_over_time(temperature_gauge[5m])",
     "legendFormat": "Temperature"
    }
   ]
  },
  {
   "title": "Average",
   "type": "gauge",
   "gridPos": { "h": 16, "w": 6, "x": 18, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "avg_over_time(temperature_gauge[5m])",
     "legendFormat": "Temperature"
    }
   ]
  },
  {
   "title": "Min Value",
   "type": "stat",
   "gridPos": { "h": 8, "w": 4, "x": 14, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "min_over_time(temperature_gauge[5m])",
     "legendFormat": "Temperature"
    }
   ]
  }
 ]
}